### PR TITLE
Accommodation and transportation info

### PR DESCRIPTION
**Pull request by jean**

### CODE REVIEW

**Comment by jean** [comment]
Don't merge yet ..

**Comment by citizen428** [comment]
Looks good so far, ping me when you need a final review :)

**Comment by jean** [comment]
The content from this page needs to be translated into https://github.com/jean/www/blob/master/site/pages/venue.th.rst
Probably the Thai version doesn't need some detail e.g. about SIM cards.

**Comment by jean** [comment]
@vtno @tonytonybell please check and add some Thai translation, then I think it can be merged.

**Comment by jean** [comment]
@citizen428 ping!

**Review by citizen428 — APPROVED** [review]
Very nice, thanks @jean! 👍

**Comment by jean** [comment]
@vtno @tonytonybell I'm going to merge, please create a new pull request for translation.

**Pull request merged**
