### PR TITLE
Confirmed Speakers

### PR DESCRIPTION
**Pull request by frawau**
Only includes abstract in presentation in talk.py.  Generated speaker list for confirmed talks

### CODE REVIEW

**Review by jean — APPROVED** [review]

**Review by jean — COMMENTED** [review]
@frawau if the th/en content is the same, then I think you can generate one post without the language spec in the title, which shows up on both sides.

**Review by jean — CHANGES_REQUESTED** [review]
Ah, looks like `talks.py` needs a tweak:

> System Message: ERROR/3 (<string>, line 351)
> Document may not end with a transition.

**Comment by frawau** [comment]
That error message is from what?

**Comment by jean** [comment]
> That error message is from what?

From `nikola build` due to invalid RST formatting. You can see it:

- if you [build locally](https://github.com/PyConTH/www#how-to-build), 
- or if you view [the built preview page](https://deploy-preview-176--serene-mestorf-5c91d0.netlify.com/speakers/) which is accessible from the github "checks" UI:
 
Confirmed Speakers by frawau · Pull Request  176 · PyConTH www

(To see the error, you can view the [version at a specific commit](https://5cc133dc72987f00074bbb68--serene-mestorf-5c91d0.netlify.com/speakers/).)

**Review by jean — APPROVED** [review]

**Pull request merged**
