### PR TITLE
Added link to trial quiz, cosmetic changes

### PR DESCRIPTION
**Pull request by frawau**

### CODE REVIEW

**Review by jean — APPROVED** [review]

**Review by jean — DISMISSED** [review]
Request from @djay : https://github.com/PyConTH/www/pull/95#issuecomment-392311014

**Review by frawau — COMMENTED** [review]
OK

**Comment by jean** [comment]
@frawau :thinking:  [this](https://github.com/PyConTH/www/pull/96/commits/881d3ed92f622d236083e1d2a47efe376ef588b6) touches on what is in the change request, namely showing it as a "seperate event". (Additionally Dylan asks that it "shouldn't overlap".)

@djay look OK now?

**Comment by frawau** [comment]
If I understand correctly, the PyLadies event will not be attended by everybody. Right?

**Comment by frawau** [comment]
I don't understand why we don't publish this. We do exactly as they do in PyCon Australia. PyLadies starts at 7:30 and finishes at 8:30 and registration open at 8:00.  And yes they do overlap, but that is what they do. The colour clearly shows they are separate events.  If they are so separated that they have nothing to do with PyCon, we should put a special page somewhere and remove them from the PyCon schedule.

**Comment by jean** [comment]
@frawau the feedback was from @djay who didn't elaborate further. 

What do you think of https://github.com/PyConTH/www/pull/101 ?
I think it makes the schedule more easily editable and style-able.

**Pull request merged**
