### PR TITLE
Add Katie post

### PR DESCRIPTION
**Pull request by vtno**

### CODE REVIEW

**Comment by vtno** [comment]
The post is added by @jean I'll close this PR 👍

**Comment by jean** [comment]
@vtno what made you think I added it? At least the English version is not on the site yet.

**Comment by jean** [comment]
@vtno I resolved the conflicts in the Thai, please check and merge if it's OK.

**Comment by vtno** [comment]
@jean There was a conflict on Katie post so I thought you've already added it. I'll check the change. Thanks!

**Comment by vtno** [comment]
The TH version looks good. Let's 🚀

**Pull request merged**
