### PR TITLE
Set "How many coins" to Thai language and shuffled things around.

### PR DESCRIPTION
**Pull request by frawau**
Removed Tavern workshop. Added Elasticsearch workshop. Added description of Elasticsearch workshop in Talk.rst

### CODE REVIEW

**Comment by frawau** [comment]
How often is the talk.rst file regenerated? I don't get why there is such a big diff between my version and the main version.

**Comment by jean** [comment]
> @frawau @djay next I'm going to add session times to the JSON, regenerate the `talks.rst`, and then I'd like to start editing the RST for syntax, placeholder avatars, etc -- **so no more regenerating from JSON ... is that OK?**

[ref](https://thailanddevs.slack.com/archives/G9TC8GMBL/p1527140495000160)

**Comment by frawau** [comment]
@jean.jordan I am OK with  regenerating with JSON.  We need to add Elastic though

**Comment by frawau** [comment]
Also... I reworked the schedule so that the days are on top of each other, to try to avoid sideway scroll. But  the HTML gets totally corrupted  when I try to test is. Why is that?

**Comment by frawau** [comment]
I am gong to delete and recreate this thing

**Pull request closed without merging**
